apiVersion: v1
kind: Service
metadata:
  name: geoserver
  labels:
    name: geoserver-service
    app: geoserver
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    name: geoserver-pod
    app: geoserver

